In [1]:
mystr = "Hello World"

In [2]:
mystr[0]

'H'

In [3]:
mystr[-2]

'l'

In [4]:
mystr[-1]

'd'

In [5]:
mystr = 'abcdefghijk'

In [6]:
mystr[2:]

'cdefghijk'

In [7]:
mystr[:3]

'abc'

In [8]:
mystr[3:6]

'def'

In [9]:
mystr[1:3]

'bc'

In [10]:
mystr[::2]

'acegik'

In [11]:
mystr[::-1]

'kjihgfedcba'

In [12]:
mylist = [1,2,3]

In [1]:
mydict = {'key1':'value1','key2':'value2'}

In [2]:
mydict

{'key1': 'value1', 'key2': 'value2'}

In [3]:
prices = {'apple':2.99,'oranges': 1.99,'milk':5.8}

In [4]:
prices['apple']

2.99

In [5]:
d = {'k1':123,'k2':[0,1,2],'k3':{'insideKey':100}}

In [6]:
d['k2']

[0, 1, 2]

In [8]:
d['k2'][2]

2

In [9]:
d['k3']['insideKey']

100

In [10]:
d = {'key1':['a','b','c']}

In [11]:
d

{'key1': ['a', 'b', 'c']}

In [13]:
d['key1'][2].upper()

'C'

In [14]:
d.keys()

dict_keys(['key1'])

In [15]:
d.values()

dict_values([['a', 'b', 'c']])

In [16]:
d.items()

dict_items([('key1', ['a', 'b', 'c'])])

In [17]:
mylist = [1,1,1,1,1,2,2,2,2,2,3,3,3,3,3]

In [20]:
myset = set()

In [21]:
set(mylist)

{1, 2, 3}

In [23]:
set('Mississippi')

{'M', 'i', 'p', 's'}

In [24]:
%%writefile myfile.txt
Hello this is a text file
this is the second line
this is the third line

Writing myfile.txt


In [25]:
myfile = open('myfile.txt')

In [26]:
myfile

<_io.TextIOWrapper name='myfile.txt' mode='r' encoding='UTF-8'>

In [27]:
pwd

'/Users/nilesh.malpeddi/Documents/Python3_Bootcamp/00-Python Object and Data Structure Basics'

In [28]:
myfile.read()

'Hello this is a text file\nthis is the second line\nthis is the third line\n'

In [29]:
myfile.read()

''

In [33]:
myfile.seek(0)

0

In [31]:
myfile.read()

'Hello this is a text file\nthis is the second line\nthis is the third line\n'

In [ ]:
myfile.seek(0)

In [34]:
myfile.readlines()

['Hello this is a text file\n',
 'this is the second line\n',
 'this is the third line\n']

In [35]:
myfile.close()

In [36]:
with open('myfile.txt') as mynewfile:
    content = mynewfile.read()

In [37]:
content

'Hello this is a text file\nthis is the second line\nthis is the third line\n'

In [41]:
%%writefile myfile.txt
One on First
Two on Second
Three on Thrid

Overwriting myfile.txt


In [42]:
with open('myfile.txt',mode='r') as f:
    print(f.read())

One on First
Two on Second
Three on Thrid



In [43]:
with open('myfile.txt',mode='a') as f:
    f.write('Four on Fourth')

In [44]:
with open('myfile.txt',mode='r') as f:
    print(f.read())

One on First
Two on Second
Three on Thrid
Four on Fourth


In [45]:
d = {'k1':1,'k2':2,'k3':3}
for item in d.items():
    print(item)

('k1', 1)
('k2', 2)
('k3', 3)


In [46]:
d = {'k1':1,'k2':2,'k3':3}
for key,value in d.items():
    print(key)
    print(value)

k1
1
k2
2
k3
3


In [47]:
word = 'abcde'
for item in enumerate(word):
    print(item)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')
(4, 'e')


In [48]:
word = 'abcde'
for index,letter in enumerate(word):
    print(index)
    print(letter)

0
a
1
b
2
c
3
d
4
e


In [51]:
mylist1 = [1,2,3]
mylist2 = ['a','b','c']
for item in zip(mylist1,mylist2):
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')


In [50]:
mylist1 = [1,2,3]
mylist2 = ['a','b','c']
for item in zip(mylist1,mylist2):
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')


In [2]:
mylist1 = [1,2,3,4,5,6]
mylist2 = ['a','b','c']
mylist3 = [100,200,300]
for item in zip(mylist1,mylist2,mylist3):
    print(item)

(1, 'a', 100)
(2, 'b', 200)
(3, 'c', 300)


In [3]:
list(zip(mylist1,mylist2,mylist3))

[(1, 'a', 100), (2, 'b', 200), (3, 'c', 300)]

In [4]:
'x' in [1,2,3]

False

In [5]:
'x' in ['x','y','z']

True

In [6]:
from random import shuffle

In [7]:
mylist = [1,2,3,4,5,6,7,8,9,10]

In [10]:
shuffle(mylist)
mylist

[2, 5, 7, 4, 1, 6, 8, 9, 10, 3]

In [11]:
from random import randint

In [12]:
randint(0,100)

75

In [13]:
mystring = 'hello'

In [14]:
mylist = []
for letter in mystring:
    mylist.append(letter)

mylist

['h', 'e', 'l', 'l', 'o']

In [16]:
mylist = [letter for letter in mystring]
mylist

['h', 'e', 'l', 'l', 'o']

In [17]:
mylist = [x for x in range(0,11)]
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
mylist = [x**2 for x in range(0,11)]
mylist

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [19]:
mylist = [x for x in range(0,11) if x%2==0]
mylist

[0, 2, 4, 6, 8, 10]

In [21]:
mylist = [x**2 for x in range(0,11) if x%2==0]
mylist

[0, 4, 16, 36, 64, 100]

In [23]:
celcius = [0,10,20,34.5]
far = [((9/5)*temp+32) for temp in celcius]
far

[32.0, 50.0, 68.0, 94.1]

In [24]:
results = [x if x%2==0 else 'Odd' for x in range(0,11)]
results

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd', 10]

In [25]:
mylist = []
for x in [2,4,6]:
    for y in [1,10,1000]:
        mylist.append(x*y)

mylist

[2, 20, 2000, 4, 40, 4000, 6, 60, 6000]

In [26]:
mylist = [x*y for x in [2,4,6] for y in [1,10,1000]]
mylist

[2, 20, 2000, 4, 40, 4000, 6, 60, 6000]

In [1]:
mylist = [1,2,3,4]

In [2]:
mylist.pop(1)

2

In [3]:
mylist

[1, 3, 4]

In [1]:
def dog_check(mystring):
    return 'dog' in mystring.lower()

In [3]:
dog_check('Dog')

True

In [4]:
def pig_latin(word):
    firstletter = word[0]
    # check if vowel
    if firstletter in 'aeiou':
        pig_word = word+'ay'
    else:
        pig_word = word[1:]+firstletter+'ay'
    
    return pig_word

In [6]:
pig_latin('word')

'ordway'

In [7]:
def myfunc(*args):
    return sum(args)*0.05

In [9]:
myfunc(40,60,100,1,34)

11.75

In [10]:
def myfunc(*args):
    print(args)

In [22]:
myt = (1,2,3,4,5)

In [28]:
for t in myt:
    print(t)

1
2
3
4
5


In [31]:
def myfunc(*args):
    mylist=[]
    for i in args:
        if i%2==0:
            mylist.append(i)
    return mylist

In [32]:
myfunc(5,6,7,8)

[6, 8]

In [38]:
strRet=''

In [39]:
strRet=strRet+'a'

In [44]:
strRet

'a'

In [42]:
strRet[0].upper()

'A'

In [11]:
myfunc(40,60,100,1,34)

(40, 60, 100, 1, 34)


In [14]:
def myfunc(*test):
    print(test)

In [15]:
myfunc(40,60,100,1,34,100,200)

(40, 60, 100, 1, 34, 100, 200)


In [20]:
def myfunc(**kwargs):
    print(kwargs)
    if 'fruit' in kwargs:
        print('My fruit of choice is {}'.format(kwargs['fruit']))
    else:
        print('I did not find any fruit here')

In [21]:
myfunc(fruit='apple',veggie='lettuce')

{'fruit': 'apple', 'veggie': 'lettuce'}
My fruit of choice is apple


In [2]:
 def square(num):
        return num**2

In [3]:
my_nums = [1,2,3,4,5]

In [4]:
for item in map(square,my_nums):
    print(item)

1
4
9
16
25


In [5]:
list(map(square,my_nums))

[1, 4, 9, 16, 25]

In [8]:
map(square,my_nums)

In [9]:
temp=[0,22.5,40,100]

In [11]:
list(map(lambda T: (9.0/5)*T+32,temp))

[32.0, 72.5, 104.0, 212.0]

In [9]:
def splicer(mystring):
    if len(mystring)%2==0:
        return 'Even'
    else:
        return mystring[0]

In [10]:
mystr = ['Andy','Eve','Sally','Devansh','Tejal','Sonali','Nilesh']

In [11]:
list(map(splicer,mystr))

['Even', 'E', 'S', 'D', 'T', 'Even', 'Even']

In [13]:
def check_num(num):
    return num%2==0

In [18]:
mynums = [1,2,3,4,5,6]
mynums

[1, 2, 3, 4, 5, 6]

In [19]:
for n in filter(check_num,mynums):
    print(n)

2
4
6


In [20]:
list(filter(check_num,mynums))

[2, 4, 6]

In [21]:
def square(num): return num**2

In [22]:
square(3)

9

In [24]:
square = lambda num:num**2

In [25]:
square(9)

81

In [26]:
list(map(lambda num:num**2,mynums))

[1, 4, 9, 16, 25, 36]

In [27]:
list(filter(lambda num:num%2==0,mynums))

[2, 4, 6]

In [28]:
mystr

['Andy', 'Eve', 'Sally', 'Devansh', 'Tejal', 'Sonali', 'Nilesh']

In [29]:
list(map(lambda x:x[0],mystr))

['A', 'E', 'S', 'D', 'T', 'S', 'N']

In [30]:
list(map(lambda x:x[::-1],mystr))

['ydnA', 'evE', 'yllaS', 'hsnaveD', 'lajeT', 'ilanoS', 'hseliN']

In [38]:
# Global
name = 'This is a global string'

def greet():
    # Enclosing
    # name='Sammy'
    
    def hello():
        # Local
        #name='I am local'
        print('Hello ' +name)
        
    hello()

In [39]:
greet()

Hello This is a global string


In [2]:
from collections import Counter

In [4]:
l = [1,2,3,1,1,1,1,2,2,3,4,2,3,4,4,5]

In [5]:
Counter(l)

Counter({1: 5, 2: 4, 3: 3, 4: 3, 5: 1})

In [6]:
s = 'aasssdddffffaaadddeeefffsssbbbbaaa'

In [7]:
Counter(s)

Counter({'a': 8, 's': 6, 'd': 6, 'f': 7, 'e': 3, 'b': 4})

In [8]:
ss = 'How many time does each word word showed showed up up sentnce hello world word world'

In [9]:
Counter(ss.split())

Counter({'How': 1,
         'many': 1,
         'time': 1,
         'does': 1,
         'each': 1,
         'word': 3,
         'showed': 2,
         'up': 2,
         'sentnce': 1,
         'hello': 1,
         'world': 2})

In [18]:
c = Counter(ss.split())

In [19]:
c.most_common(3)

[('word', 3), ('showed', 2), ('up', 2)]

In [20]:
from collections import defaultdict

In [11]:
def arryproduct(numarray):
    mynumlist = []
    mycurInd = 0
    mysubInd = 0
    for num in numarray:
        arrprodnum = 1
        for subnum in numarray:
            if mycurInd!=mysubInd:
                arrprodnum = arrprodnum*subnum
                
            mysubInd+=1
        mynumlist.append(arrprodnum)
        mysubInd=0
        mycurInd+=1
    
    return mynumlist

In [12]:
arryproduct([2,2,2])

[4, 4, 4]

In [13]:
arryproduct([2,4,8])

[32, 16, 8]

In [1]:
import re

In [2]:
patterns = ['term1','term2']

In [3]:
text = 'This is string with term1, but not the other term'

In [4]:
for pattern in patterns:
    print('Searching for {} in : \n{}'.format(pattern,text))
    
    if re.search(pattern,text):
        print('\nMatch found\n')
    else:
        print('\nMatch not found\n')

Searching for term1 in : 
This is string with term1, but not the other term

Match found

Searching for term2 in : 
This is string with term1, but not the other term

Match not found



In [5]:
match = re.search(patterns[0],text)

In [6]:
type(match)

_sre.SRE_Match

In [7]:
match.start()

20

In [8]:
match.end()

25

In [9]:
split_term = '@'
phrase = 'what is your email, is it hello@gmail.com?'

In [10]:
re.split(split_term,phrase)

['what is your email, is it hello', 'gmail.com?']

In [11]:
phrase.split('@')

['what is your email, is it hello', 'gmail.com?']

In [13]:
re.findall('is',phrase)

['is', 'is']

In [15]:
def multi_re_find(patterns,phrase):
    '''
    Takes in a list of regex patterns
    Prints a list of all matches
    '''
    for pattern in patterns:
        print('Searching the phrase using the re check: {}'.format(pattern))
        print(re.findall(pattern,phrase))
        print('\n')

In [16]:
test_phrase = 'sdsd..sssddd...sdddsddd...dsds...dsssss...sdddd'
test_patterns = ['sd*', # s followed by zero or more d's
                'sd+', # s followed by one or more d's
                'sd?', # s follwed by zero or one d's
                'sd{3}', # s followed by three d's
                'sd{2,3}' # s followed by two or three d's
                ]
multi_re_find(test_patterns,test_phrase)

Searching the phrase using the re check: sd*
['sd', 'sd', 's', 's', 'sddd', 'sddd', 'sddd', 'sd', 's', 's', 's', 's', 's', 's', 'sdddd']


Searching the phrase using the re check: sd+
['sd', 'sd', 'sddd', 'sddd', 'sddd', 'sd', 'sdddd']


Searching the phrase using the re check: sd?
['sd', 'sd', 's', 's', 'sd', 'sd', 'sd', 'sd', 's', 's', 's', 's', 's', 's', 'sd']


Searching the phrase using the re check: sd{3}
['sddd', 'sddd', 'sddd', 'sddd']


Searching the phrase using the re check: sd{2,3}
['sddd', 'sddd', 'sddd', 'sddd']




In [ ]:
test_phrase = 'sdsd..sssddd...sdddsddd...dsds...dsssss...sdddd'
test_patterns = ['sd*', # s followed by zero or more d's
                'sd+', # s followed by one or more d's
                'sd?', # s follwed by zero or one d's
                'sd{3}', # s followed by three d's
                'sd{2,3}' # s followed by two or three d's
                ]
multi_re_find(test_patterns,test_phrase)

In [23]:
test_phrase = 'This is a string! But it has punctutation. How can we remove it?'

In [25]:
re.findall('[^!.? ]+',test_phrase)

['This',
 'is',
 'a',
 'string',
 'But',
 'it',
 'has',
 'punctutation',
 'How',
 'can',
 'we',
 'remove',
 'it']

In [22]:
re.findall('[a-zA-Z]+',test_phrase)

['This',
 'is',
 'a',
 'string',
 'But',
 'it',
 'has',
 'punctutation',
 'How',
 'can',
 'we',
 'remove',
 'it']

In [29]:
test_phrase = 'This is an example sentence. Lets see if we can find some letters.'
test_patterns=['[a-z]+', # sequences of lower case letters
               '[A-Z]+', # sequences of upper case letters
               '[a-zA-Z]+', # sequences of lower or upper case letters
               '[A-Z][a-z]+' # one upper case letter followed by lower case letters
               ]

multi_re_find(test_patterns,test_phrase)

Searching the phrase using the re check: [a-z]+
['his', 'is', 'an', 'example', 'sentence', 'ets', 'see', 'if', 'we', 'can', 'find', 'some', 'letters']


Searching the phrase using the re check: [A-Z]+
['T', 'L']


Searching the phrase using the re check: [a-zA-Z]+
['This', 'is', 'an', 'example', 'sentence', 'Lets', 'see', 'if', 'we', 'can', 'find', 'some', 'letters']


Searching the phrase using the re check: [A-Z][a-z]+
['This', 'Lets']




In [30]:
test_phrase = 'This is a string with some numbers 1233 and a symbol #hashtag'
test_patterns = [r'\d+', # sequence of digits
                 r'\D+', # sequence of non-digits
                 r'\s+', # sequence of whitespace
                 r'\S+', # sequence of non-whitespace
                 r'\w+', # alphanumeric characters
                 r'\W+', # non alphanumeric
                ]

multi_re_find(test_patterns,test_phrase)

Searching the phrase using the re check: \d+
['1233']


Searching the phrase using the re check: \D+
['This is a string with some numbers ', ' and a symbol #hashtag']


Searching the phrase using the re check: \s+
[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']


Searching the phrase using the re check: \S+
['This', 'is', 'a', 'string', 'with', 'some', 'numbers', '1233', 'and', 'a', 'symbol', '#hashtag']


Searching the phrase using the re check: \w+
['This', 'is', 'a', 'string', 'with', 'some', 'numbers', '1233', 'and', 'a', 'symbol', 'hashtag']


Searching the phrase using the re check: \W+
[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' #']




In [31]:
s = 'hiihhihihihhhi'

In [32]:
s.partition('i')

('h', 'i', 'ihhihihihhhi')

In [33]:
s = set()

In [34]:
s.add(1)

In [35]:
s.add(2)

In [36]:
s

{1, 2}

In [37]:
s = {1,2,3,3,4}

In [38]:
s

{1, 2, 3, 4}

In [39]:
sc=s.copy()

In [40]:
s

{1, 2, 3, 4}

In [41]:
sc

{1, 2, 3, 4}

In [42]:
s.add(5)

In [43]:
s

{1, 2, 3, 4, 5}

In [44]:
sc

{1, 2, 3, 4}

In [45]:
s.difference(sc)

{5}

In [46]:
sc.difference(s)

set()

In [47]:
s1 = {1,2,3}
s2 = {1,4,5}

In [48]:
s1.difference_update(s2)

In [49]:
s1

{2, 3}

In [50]:
s2

{1, 4, 5}

In [51]:
s1={1,2,3}
s2={1,2,4}

In [52]:
s1.intersection(s2)

{1, 2}

In [54]:
s1

{1, 2, 3}

In [55]:
s1.intersection_update(s2)

In [56]:
s1

{1, 2}

In [1]:
s1 = {1,2}
s2 = {1,2,4}
s3 = {5}

In [2]:
s1.isdisjoint(s2)

False

In [3]:
s1.isdisjoint(s3)

True

In [5]:
s1.issubset(s2)

True

In [6]:
s2.issuperset(s1)

True

In [7]:
s1

{1, 2}

In [8]:
s2

{1, 2, 4}

In [9]:
s1.symmetric_difference(s2)

{4}

In [10]:
s2.symmetric_difference(s1)

{4}

In [11]:
s1.union(s2)

{1, 2, 4}

In [12]:
s1.update(s2)

In [13]:
s1

{1, 2, 4}

In [14]:
s2

{1, 2, 4}

In [19]:
d={'k1':1,'k2':2}

In [66]:
{x:x**3 for x in range(10)}

{0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729}

In [17]:
{k:v**2 for k,v in zip(['a','b'],range(2))}

{'a': 0, 'b': 1}

In [21]:
for k in d.items():
    print(k)

('k1', 1)
('k2', 2)


In [22]:
l = [1,2,3]

In [23]:
l.append(4)

In [24]:
l

[1, 2, 3, 4]

In [25]:
l.count(10)

0

In [26]:
l.count(2)

1

In [27]:
x = [1,2,3]

In [28]:
x.append([4,5])

In [29]:
x

[1, 2, 3, [4, 5]]

In [30]:
x = [1,2,3]

In [31]:
x.extend([4,5])

In [32]:
x

[1, 2, 3, 4, 5]

In [37]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 
          'banana']

In [38]:
type(fruits)

list

In [39]:
fruits.count('apple')

2

In [40]:
fruits.count('tangerine')

0

In [41]:
fruits.index('banana')

3

In [42]:
fruits.index('banana',4)

6

In [43]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [44]:
fruits.append('grape')

In [45]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [46]:
fruits.pop()

'pear'

In [47]:
stack = [3,4,5]

In [48]:
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [49]:
stack.pop()

7

In [50]:
stack

[3, 4, 5, 6]

In [51]:
from collections import deque

In [52]:
queue = deque(["Erick","John","Michael"])

In [53]:
queue.append('Terry')

In [54]:
queue.append('Graham')

In [55]:
queue

deque(['Erick', 'John', 'Michael', 'Terry', 'Graham'])

In [56]:
queue.popleft()

'Erick'

In [57]:
queue.popleft()

'John'

In [58]:
queue

deque(['Michael', 'Terry', 'Graham'])

In [60]:
squares = []
for x in range(10):
    squares.append(x**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [62]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [64]:
squares = list(map(lambda x:x**2,range(10)))
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [65]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [1]:
[(x,y) for x in [1,2,3] for y in [3,1,4] if x!=y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [2]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x!=y:
            combs.append((x,y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [3]:
[(x,y) for x in [1,2,3] for y in [3,1,4] if x!=y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [4]:
vec = [-4,-2,0,2,4]

In [5]:
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [6]:
[x for x in vec if x>0]

[2, 4]

In [7]:
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [8]:
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']

In [9]:
[f.strip() for f in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [10]:
[(x,x**2) for x in range(10)]

[(0, 0),
 (1, 1),
 (2, 4),
 (3, 9),
 (4, 16),
 (5, 25),
 (6, 36),
 (7, 49),
 (8, 64),
 (9, 81)]

In [11]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
[num for elment in vec for num in elment]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
mylist = []
for nums in vec:
    for el in nums:
        mylist.append(el)
        
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
[num for nums in vec for num in nums]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
[el for nums in vec for el in nums]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
from math import pi
[str(round(pi,i)) for i in range(1,6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

In [21]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [24]:
#transpose rows and columns
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [28]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [30]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [31]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

In [32]:
x = [1, 2, 3]
y = [4, 5, 6]

In [37]:
list(zip(x,y))

[(1, 4), (2, 5), (3, 6)]

In [50]:
a = [-1, 1, 66.25, 333, 333, 1234.5]

In [51]:
del a[0]

In [52]:
a

[1, 66.25, 333, 333, 1234.5]

In [53]:
del a[2:4]

In [54]:
a

[1, 66.25, 1234.5]

In [1]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}

In [2]:
basket

{'apple', 'banana', 'orange', 'pear'}

In [3]:
'orange' in basket

True

In [4]:
'test' in basket

False

In [13]:
a = set('abracadabra')
b = set('alacazam')

In [14]:
a ^ b

{'b', 'd', 'l', 'm', 'r', 'z'}

In [6]:
a

{'a', 'b', 'c', 'd', 'r'}

In [7]:
b

{'a', 'c', 'l', 'm', 'z'}

In [8]:
a-b

{'b', 'd', 'r'}

In [9]:
b-a

{'l', 'm', 'z'}

In [10]:
a|b

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [11]:
a & b

{'a', 'c'}

In [12]:
a ^ b

{'b', 'd', 'l', 'm', 'r', 'z'}

In [15]:
tel = {'jack':4098,'sape':4139}

In [16]:
tel['guido']=4127

In [17]:
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [18]:
del tel['sape']

In [19]:
tel['irv']=4127

In [20]:
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [21]:
list(tel)

['jack', 'guido', 'irv']

In [22]:
sorted(tel)

['guido', 'irv', 'jack']

In [23]:
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [24]:
dict([('sape',4139),('guido',4127),('jack',4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [25]:
{x:x**2 for x in (2,4,6)}

{2: 4, 4: 16, 6: 36}

In [26]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}

In [27]:
for k,v in knights.items():
    print(k,v)

gallahad the pure
robin the brave


In [28]:
for i,v in enumerate(['tic','tac','toe']):
    print(i,v)

0 tic
1 tac
2 toe


In [29]:
x=[1,2,3]
y=[4,5,6,7]

In [31]:
list(zip(x,y))

[(1, 4), (2, 5), (3, 6)]

In [33]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']

In [34]:
for q,a in zip(questions,answers):
    print('What is your {0}? It is {1}.'.format(q,a))

What is your name? It is lancelot.
What is your quest? It is the holy grail.
What is your favorite color? It is blue.


In [35]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [36]:
for i in reversed(range(1,10,2)):
    print(i)

9
7
5
3
1


In [39]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

In [40]:
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


In [42]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

In [43]:
string1,string2,string3='','Trondheim','Hammer Dance'

In [49]:
non_null = string1 or string2 or string3

In [50]:
non_null

'Trondheim'

In [51]:
import numpy as np

In [53]:
myarray = np.array([[1,2,3,4],[5,6,7,8]],dtype=np.int64)
print(myarray)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros((3,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [63]:
np.random.random((2,2))

array([[0.15331934, 0.48409379],
       [0.41646937, 0.26419984]])

In [64]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [68]:
np.full((2,3,5),1)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [73]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [72]:
??np.arange

In [76]:
np.linspace(0,2,100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [77]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
??np.identity

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
print(myarray.ndim)

2


In [82]:
myarray.ndim

2

In [83]:
myarray.size

8

In [84]:
myarray.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [86]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
myarray.itemsize

8

In [87]:
myarray.nbytes

64

In [88]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
x = np.ones((3,4))

In [92]:
x.shape

(3, 4)

In [93]:
y=np.arange(4)

In [95]:
y.shape

(4,)

In [96]:
x-y

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [97]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
y

array([0, 1, 2, 3])

In [105]:
x=np.ones((2,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
y=np.random.random((1,1,4))
y

array([[[0.89058978, 0.92473803, 0.32885312, 0.60275192]]])

In [110]:
x+y

array([[[1.89058978, 1.92473803, 1.32885312, 1.60275192],
        [1.89058978, 1.92473803, 1.32885312, 1.60275192]]])

In [111]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [112]:
y

array([[[0.89058978, 0.92473803, 0.32885312, 0.60275192]]])

In [113]:
np.add(x,y)

array([[[1.89058978, 1.92473803, 1.32885312, 1.60275192],
        [1.89058978, 1.92473803, 1.32885312, 1.60275192]]])

In [114]:
np.subtract(x,y)

array([[[0.10941022, 0.07526197, 0.67114688, 0.39724808],
        [0.10941022, 0.07526197, 0.67114688, 0.39724808]]])

In [115]:
np.multiply(x,y)

array([[[0.89058978, 0.92473803, 0.32885312, 0.60275192],
        [0.89058978, 0.92473803, 0.32885312, 0.60275192]]])

In [116]:
np.divide(x,y)

array([[[1.12285142, 1.08138734, 3.04087124, 1.65905733],
        [1.12285142, 1.08138734, 3.04087124, 1.65905733]]])

In [117]:
np.remainder(x,y)

array([[[0.10941022, 0.07526197, 0.01344064, 0.39724808],
        [0.10941022, 0.07526197, 0.01344064, 0.39724808]]])

In [121]:
y = np.random.random((5,2,4))
y

array([[[0.1810818 , 0.34714337, 0.2623805 , 0.08138084],
        [0.28781624, 0.43566439, 0.41570553, 0.60976972]],

       [[0.48618048, 0.31547501, 0.68746005, 0.94529564],
        [0.56405176, 0.22421992, 0.45138908, 0.844883  ]],

       [[0.30655228, 0.30323516, 0.10708437, 0.40095602],
        [0.35734896, 0.26139014, 0.91408088, 0.06727375]],

       [[0.26119586, 0.92065162, 0.41501562, 0.16142282],
        [0.38445956, 0.44944716, 0.86324604, 0.86075572]],

       [[0.85925658, 0.96372597, 0.56689598, 0.54352562],
        [0.74308951, 0.78988415, 0.82127202, 0.999629  ]]])

In [122]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
myarray[1]

array([5, 6, 7, 8])

In [124]:
myarray[1][2]

7

In [125]:
myarray[1,2]

7

In [128]:
myarray[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
myarray[0:1,0:2]

array([[1, 2]])

In [130]:
myarray[0:2,1]

array([2, 6])

In [131]:
myarray[0:2,2]

array([3, 7])

In [132]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
myarray[myarray<7]

array([1, 2, 3, 4, 5, 6])

In [136]:
bigger_than_3 = (myarray>=3)

In [137]:
myarray[bigger_than_3]

array([3, 4, 5, 6, 7, 8])

In [138]:
bigger_than_3

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [141]:
myarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [142]:
print(myarray[[1, 0, 1, 0],[0, 1, 2, 0]])

[5 2 7 1]


In [143]:
print(myarray[[1, 0, 1, 0]][:,[0,1,2,0]])

[[5 6 7 5]
 [1 2 3 1]
 [5 6 7 5]
 [1 2 3 1]]


In [144]:
myarray[[1,0,1,0]]

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [145]:
print(myarray)

[[1 2 3 4]
 [5 6 7 8]]


In [146]:
print(np.transpose(myarray))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [147]:
print(myarray.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [148]:
myarray[:,[0,1,2,0]]

array([[1, 2, 3, 1],
       [5, 6, 7, 5]])

In [149]:
print(np.lookfor("mean"))

Search results for 'mean'
-------------------------
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.array_equiv
    Returns True if input arrays are shape consistent and all elements equal.
numpy.matrix.mean
    Returns the average of the matrix elements along the given axis.
numpy.chararray.mean
    Returns the average of the array elements along given axis.
numpy.ma.anom
    Compute the anomalies (deviations from the arithmetic mean)
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.ma.MaskedArray.anom
    Compute the anomalies (deviations from the arithmetic mean)
numpy.polynomial.polyutils.trimcoef
    Remove "small" "trailing" coefficients from a polynomial.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.pad
 

In [150]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [151]:
x.shape

(2, 4)

In [153]:
??np.ones

In [154]:
x = np.ones((3,4))

In [155]:
x.shape

(3, 4)

In [159]:
np.resize(x,(6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [161]:
x.shape

(3, 4)

In [164]:
x.resize((6,4))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [165]:
newarray = np.append(myarray,[7,8,9,10])

In [166]:
newarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  7,  8,  9, 10])

In [167]:
new2darray = np.append(myarray,[[7],[8]],axis=1)
new2darray

array([[1, 2, 3, 4, 7],
       [5, 6, 7, 8, 8]])

In [168]:
print(np.concatenate((myarray,x)))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [169]:
print(np.vstack((myarray,x)))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [170]:
print(np.r_((myarray,x)))

TypeError: 'RClass' object is not callable

In [171]:
print(np.hstack((myarray,x)))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [13]:
list(map(lambda x:x,'human'))

['h', 'u', 'm', 'a', 'n']

In [16]:
[x for x in range(100) if x%2==0 if x%5==0]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [17]:
["Even" if i%2==0 else "Odd" for i in range(10)]

['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']

In [18]:
['Even' if i%2==0 else 'Odd' for i in range(10)]

['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']

In [20]:
transposed = []
matrix = [[1,2,3,4],[4,5,6,8]]

In [22]:
for i in range(len(matrix[0])):
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)
transposed

[[1, 4], [2, 5], [3, 6], [4, 8]]

In [23]:
matrix

[[1, 2, 3, 4], [4, 5, 6, 8]]

In [24]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 4], [2, 5], [3, 6], [4, 8]]

In [21]:
matrix[0]

[1, 2, 3, 4]

In [1]:
126%9

0

In [2]:
126%4

2

In [3]:
126%3

0

In [4]:
4%2

0

In [1]:
1/25

0.04

In [2]:
2**2

4

In [3]:
2**3

8

In [4]:
5**-2

0.04

In [6]:
5**(1/25)

1.0664949422083674

In [7]:
import math

In [9]:
math.log(5**(1/25))

0.06437751649736409

In [10]:
math.log(10)

2.302585092994046

In [11]:
math.log(9)

2.1972245773362196

In [12]:
math.log(10000)

9.210340371976184

In [1]:
2**5

32